name: Deploy Jekyll with GitHub Pages dependencies preinstalled
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: 'npm install, build, and test'
        run: |
          npm install
          npm run build:prod
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: deploy_dist
          path: dist/motorhead-performance
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: '${{ steps.deploy-to-webapp.outputs.webapp-url }}'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: deploy_dist
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: motorhead-performance
    slot-name: production
    publish-profile: '${{ secrets.ACCESS_TOKEN }}'
    package: .
